name: webrtc
channels:
  - anaconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py314hacdc0fc_0
  - mkl_fft=2.1.1=py314h2be417e_0
  - mkl_random=1.3.0=py314hda4e5d8_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyh0d26453_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.14.2=h90eec9f_101_cp314
  - python_abi=3.14=2_cp314
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.1=he0a8d7e_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=hd233ad5_2
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aioice==0.10.2
      - aiortc==1.14.0
      - av==16.1.0
      - cffi==2.0.0
      - cryptography==46.0.3
      - dnspython==2.8.0
      - google-crc32c==1.8.0
      - ifaddr==0.2.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pycparser==2.23
      - pyee==13.0.0
      - pylibsrtp==1.0.0
      - pyopenssl==25.3.0
      - typing-extensions==4.15.0
prefix: /home/gossfr01@bureautique.uqar.qc.ca/miniconda3/envs/webrtc
